Workflow/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MySql.Data.MySqlClient;
using Workflow.Models;

namespace Workflow.Controllers
{
    public class LoginController : BaseController
    {
        // GET: /<controller>/
        private readonly WorkflowContext _context;

        public LoginController(WorkflowContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            Console.Write("test");
            return View();
        }

        public IActionResult Login(string username, string password)
        {
            
            using (MySqlConnection connection = new MySqlConnection(ConnectionString))
            {
                connection.Open();
                {

                    MySqlCommand cmd = connection.CreateCommand();
                    cmd.CommandText = "SELECT * FROM user WHERE Username = '" + username + "';";

                    MySqlDataReader reader = cmd.ExecuteReader();
                    while (reader.Read())
                    {
                        if (BCrypt.Net.BCrypt.Verify(password, (string)reader.GetValue(2)))
                        {
                            int UserID = (int)reader.GetValue(0);
                            HttpContext.Session.SetInt32(SessionId, UserID);
                            CurrentUser = _context.User.Find(UserID);
                        }
                    }

                }
                return Redirect("~/Home/Index");
            }
        }

        public ActionResult Logout()
        {
            HttpContext.Session.Remove(SessionId);
            return Redirect("~/Login/Index");
        }
    }
}

Workflow/Controllers/PTaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Workflow.Models;

namespace Workflow.Controllers
{
    public class PTaskController :BaseController
    {
        private readonly WorkflowContext _context;

        public PTaskController(WorkflowContext context)
        {
            _context = context;
        }


        // GET: PTask
#pragma warning disable CS1998 // Async method lacks 'await' operators and will run synchronously
        public async Task<IActionResult> Index()
#pragma warning restore CS1998 // Async method lacks 'await' operators and will run synchronously
        {
            List<Ptask> list = new List<Ptask>();

            foreach (AssignedTask a in _context.AssignedTask.Where(a => a.UserId == CurrentUser.UserId))
            {
                list.Add(_context.Ptask.Include(p => p.TaskList).Include(p => p.TaskProject).FirstOrDefault(m => m.TaskId == a.TaskId));
            }

            return View(list);
        }

        // GET: PTask/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ptask = await _context.Ptask
                .Include(p => p.TaskList)
                .Include(p => p.TaskProject)
                .FirstOrDefaultAsync(m => m.TaskId == id);
            if (ptask == null)
            {
                return NotFound();
            }
            return View(ptask);
        }

        // GET: PTask/Create
        //public IActionResult Create(int id)
        //{
        //    ViewData["TaskListId"] = new SelectList(_context.TaskList, "TaskListId", "ListName");
        //    ViewData["TaskProjectId"] = new SelectList(_context.Project, "ProjectId", "ProjectName");

        //    ViewBag.tasklist = _context.TaskList.Where(t => t.ProjectId == id).ToList();
        //    ViewBag.project = _context.Project.Find(id);

        //    return View();
        //}

        // POST: PTask/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public void Create(string TaskName, string Description, string Priority, int TaskProjectId, int? TaskListId = null, DateTime? TaskDeadline = null)
        {
            Ptask t = new Ptask();
            t.TaskName = TaskName;
            t.Description = Description;
            t.Priority = Priority;

            if (TaskDeadline != null)
            {
                t.TaskDeadline = TaskDeadline;
            }
            t.TaskProjectId = TaskProjectId;
            if (TaskListId != null)
            {
                t.TaskListId = TaskListId;
            }
            
            _context.Add(t);
            _context.SaveChanges();

            EventController.NewEvent(TaskProjectId, CurrentUser.UserId, "new task", null, t.TaskId, TaskListId, false, null, null);

            Response.Redirect("/Project/Details/" + TaskProjectId);
        }

        // GET: PTask/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ptask = await _context.Ptask.FindAsync(id);
            if (ptask == null)
            {
                return NotFound();
            }
            ViewData["TaskListId"] = new SelectList(_context.TaskList, "TaskListId", "ListName", ptask.TaskListId);
            ViewData["TaskProjectId"] = new SelectList(_context.Project, "ProjectId", "ProjectName", ptask.TaskProjectId);
            ViewBag.tasklist = _context.TaskList.Where(t => t.ProjectId == ptask.TaskProjectId).ToList();
            ViewBag.project = _context.Project.Find(ptask.TaskProjectId);
            return View(ptask);
        }

        // POST: PTask/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TaskId,TaskName,Description,Priority,TaskCreationDate,TaskDeadline,CompletionDate,TaskProjectId,TaskListId")] Ptask ptask)
        {
            if (id != ptask.TaskId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ptask);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PtaskExists(ptask.TaskId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TaskListId"] = new SelectList(_context.TaskList, "TaskListId", "TaskListId", ptask.TaskListId);
            ViewData["TaskProjectId"] = new SelectList(_context.Project, "ProjectId", "ProjectName", ptask.TaskProjectId);
            Response.Redirect("/Project/Details/" + ptask.TaskProjectId);
            return View(ptask);
        }

        // GET: PTask/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ptask = await _context.Ptask
                .Include(p => p.TaskList)
                .Include(p => p.TaskProject)
                .FirstOrDefaultAsync(m => m.TaskId == id);
            if (ptask == null)
            {
                return NotFound();
            }
            return View(ptask);
        }

        // POST: PTask/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ptask = await _context.Ptask.FindAsync(id);
            var i = ptask.TaskProjectId;

            ptask.Deleted = 1;
            _context.SaveChanges();
            EventController.NewEvent(ptask.TaskProjectId.Value, CurrentUser.UserId, "remove task", null, ptask.TaskId, ptask.TaskListId, false, null, null);
            return Redirect("/Project/Details/" + i);
        }

        private bool PtaskExists(int id)
        {
            return _context.Ptask.Any(e => e.TaskId == id);
        }

        public void Complete(int id)
        {
            Ptask task = _context.Ptask.Find(id);
            task.CompletionDate = DateTime.Now;
            _context.SaveChanges();

            Project project = _context.Project.Find(task.TaskProjectId);

            EventController.NewEvent(project.ProjectId, CurrentUser.UserId, "finished task", project.ProjectManager, task.TaskId, null, true, true, true);

            Response.Redirect("/Project/Details/" + task.TaskProjectId);
        }

        public void RemoveComplete(int id)
        {
            Ptask task = _context.Ptask.Find(id);
            task.CompletionDate = null;
            _context.SaveChanges();

            Response.Redirect("/Project/Details/" + task.TaskProjectId);
        }

        public void Assign(int user_id, int task_id, int project_id)
        {
            Ptask task = _context.Ptask.Find(task_id);

            AssignedTask at = new AssignedTask();
            at.ProjectId = project_id;
            at.UserId = user_id;
            at.TaskId = task_id;
            _context.Add(at);
            _context.SaveChanges();

            Project p = _context.Project.Find(project_id);

            EventController.NewEvent(at.ProjectId, CurrentUser.UserId, "assigned task", user_id, task.TaskId, task.TaskListId, true, true, true);


            Response.Redirect("/Project/Details/" + project_id);
        }

        public void Unassign(int id)
        {
            AssignedTask a = _context.AssignedTask.Find(id);
            var project_id = a.ProjectId;
            _context.Remove(a);
            _context.SaveChanges();
            Response.Redirect("/Project/Details/" + project_id);
        }

        public void Restore(int id)
        {
            System.Diagnostics.Debug.WriteLine("");
            System.Diagnostics.Debug.WriteLine("");
            System.Diagnostics.Debug.WriteLine("");
            System.Diagnostics.Debug.WriteLine(id);
            System.Diagnostics.Debug.WriteLine("");
            System.Diagnostics.Debug.WriteLine("");

            Ptask ptask = _context.Ptask.Find(id);
            ptask.Deleted = 0;
            _context.SaveChanges();
            EventController.NewEvent(ptask.TaskProjectId.Value, CurrentUser.UserId, "restore task", null, ptask.TaskId, ptask.TaskListId, false, null, null);
            Response.Redirect("/Project/Details/" + ptask.TaskProjectId);
        }
    }
}

Workflow/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using Microsoft.EntityFrameworkCore;
using Workflow.Models;

namespace Workflow.Controllers
{
    public class UserController : BaseController
    {
        private readonly WorkflowContext _context;

        public UserController(WorkflowContext context)
        {
            _context = context;
        }

        // GET: User
        public async Task<IActionResult> Index()
        {
            return View(await _context.User.ToListAsync());
        }

        // GET: User/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: User/Profile/5
        public async Task<IActionResult> Profile(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // GET: User/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: User/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserId,Username,Password,FirstName,LastName,Email,PhoneNumber,Role,About")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: User/Edit/5
        public void Edit(int UserId, string Username, String Password, string FirstName, string LastName, string Email, string PhoneNumber, int Role, string About, IFormFile Image)
        {
            User user = _context.User.Find(UserId);
            user.Username = Username;
            user.Password = Password;
            user.FirstName = FirstName;
            user.LastName = LastName;
            user.Email = Email;
            user.PhoneNumber = PhoneNumber;
            user.Role = Role;
            user.About = About;

            if (Image != null)
            {
                using (var stream = new System.IO.MemoryStream())
                {
                    Image.CopyTo(stream);

                    user.Image = stream.ToArray();
                }
            }

            _context.SaveChanges();

            //Response.Redirect("/User/Details/" + UserId);
            Response.Redirect("/User/Profile/" + UserId);
        }


        ////POST: User/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Edit(int id, [Bind("UserId,Username,Password,FirstName,LastName,Email,PhoneNumber,Role,About")] User user)
        //{
        //    if (id != user.UserId)
        //    {
        //        return NotFound();
        //    }



        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            _context.Update(user);
        //            await _context.SaveChangesAsync();
        //        }
        //        catch (DbUpdateConcurrencyException)
        //        {
        //            if (!UserExists(user.UserId))
        //            {
        //                return NotFound();
        //            }
        //            else
        //            {
        //                throw;
        //            }
        //        }
        //        return RedirectToAction(nameof(Profile));
        //    }
        //    return View(user);
        //}

        //private bool UserExists(int id)
        //{
        //    return _context.User.Any(e => e.UserId == id);
        //}

        // GET: User/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.User
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: User/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.User.FindAsync(id);
            _context.User.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        // Display image from the database (byte[])
        [HttpGet]
        public async Task<IActionResult> RenderImg(int id)
        {
            var user = await _context.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return File(user.Image, "image/png");
        }


    }
}

Workflow/Views/Shared/_Layout.cshtml
@{
    bool LoggedIn = ViewBag.LoggedIn;
    var CurrentUser = ViewBag.CurrentUser;
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Workflow</title>


    <!-- font awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- MDBootstrap Datatables  -->
    <link href="css/addons/datatables.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body id="page-top" onload="moveProgress()" style="margin-bottom: 0px">
    @{
        if (LoggedIn)
        {
            <nav class="navbar navbar-expand navbar-dark bg-dark static-top" id="header">

                <a style="font-size:1.3rem" class="navbar-brand mr-1" href="index.html">W<i class="fas fa-tools fa-xs" style="padding:3px"></i>rkflow </a>

                <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
                    <i class="fas fa-bars fa-lg" style="margin-left:10px"></i>
                </button>

                <!-- Navbar -->
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown no-arrow mx-1">
                        <a class="nav-link dropdown-toggle" onclick="setNotesViewed(@CurrentUser.UserId)" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-bell fa-fw fa-lg" style="color:white"></i>
                            @{
                                if (ViewBag.notes.Count > 0)
                                {
                                    <span class="badge badge-danger @if (ViewBag.notes.Count <= 0) { Write("hidden"); }" id="notes_count">

                                        @ViewBag.notes.Count
                                    </span>
                                }
                            }
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="alertsDropdown" id="notifications">

                            @{
                                if (ViewBag.notes.Count > 0)
                                {
                                    foreach (Notification n in ViewBag.notes)
                                    {
                                        <a href="/Project/Details/@n.Event.ProjectId" class="dropdown-item note-item">
                                            <button type="button" class="noButton" onclick="removeNote(@n.Nid); return false;">&times;</button>
                                            @n.Event.GetMessage() 
                                            <div class="row">
                                                <div class="col text-secondary font-italic">@n.Event.EventDate</div>
                                            </div>
                                        </a>
                                        <div class="dropdown-divider"></div>
                                    }
                                }
                                if (ViewBag.viewedNotes.Count > 0)
                                {
                                    foreach (Notification n in ViewBag.viewedNotes)
                                    {
                                        <a href="/Project/Details/@n.Event.ProjectId" class="dropdown-item">
                                            <button type="button" class="noButton" onclick="removeNote(@n.Nid); return false;">&times;</button>
                                            @n.Event.GetMessage()
                                            <div class="row">
                                                <div class="col text-secondary font-italic">@n.Event.EventDate</div>
                                            </div>
                                        </a>
                                        <div class="dropdown-divider"></div>
                                    }
                                }
                            }

                        </div>
                    </li>
                    <li class="nav-item dropdown no-arrow">
                        <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fas fa-user-circle fa-fw fa-lg" style="color:white"></i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                            <div id="loggedInUser">@CurrentUser.Username</div>
                            <a class="dropdown-item" asp-controller="User" asp-action="Profile" asp-route-id="@CurrentUser.UserId">Profile</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-controller="Login" asp-action="Logout">Logout</a>
                        </div>
                    </li>
                </ul>

            </nav>
        }
    }

    <div id="wrapper">

        @{
            if (LoggedIn)
            {
                <!-- Sidebar -->
                <ul class="sidebar navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">
                            <i class="fas fa-fw fa-tachometer-alt"></i>
                            <span>Dashboard</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Project" asp-action="Index">
                            <i class="fas fa-laptop-code"></i>
                            <span>Projects</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="PTask" asp-action="Index">
                            <i class="fas fa-tasks"></i>
                            <span>Tasks</span>
                        </a>
                    </li>
                </ul>
            }
        }

        <div id="content-wrapper">

            <div class="container-fluid">

                <!-- Page Content -->
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>

            </div>
            <!-- /.container-fluid -->

                    @{
            if (LoggedIn)
            {
                <footer class="border-top footer text-muted">
                    <div class="container">
                        &copy; 2019 - Workflow - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </div>
                </footer>
            } else {
                <footer class="border-top footer text-muted" id="footer_login">
                        &copy; 2019 - Workflow 
                </footer>
            }
        }
        

        </div>
        <!-- /.content-wrapper -->

    </div>
    <!-- /#wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4="></script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- MDBootstrap Datatables  -->
    <script type="text/javascript" src="js/addons/datatables.min.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>